DROP DATABASE IF EXISTS BULLCOW;

CREATE DATABASE BULLCOW;

USE BULLCOW;

CREATE TABLE `Game`(
GameId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
CorrectAnswerKey CHAR(4) NOT NULL,
GameStatus TINYINT NOT NULL
);

CREATE TABLE `Round` (
RoundId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Time TIMESTAMP NOT NULL,
GuessResultExact VARCHAR(45) NOT NULL,
GuessResultPartial VARCHAR(45) NOT NULL,
UserGuessKey INT NOT NULL,
GameId INT NOT NULL,
-- FK GameId
FOREIGN KEY fk_GameId (GameId)
	REFERENCES `Game` (GameId)
);

